### ISSUE TITLE
Update sentiment.py

### ISSUE THREAD

**Issue by sadia-kd** [Jonqora/VibeCheckMyProf#43]
## Task
- sentiment.py is the python script that will run the sentiment analysis on RateMyProf reviews. It needs to be edited to incorporate the new models finalized and ensure the output is returned in JSON format with the original data.  

### Problem or Gap
- The current version of sentiment.py does not include the finalized models, nor does it use consistent variable names, as the other scripts, from the sentiment analysis results. Additionally, testing is required to validate the functionality and data format using sample data.

### Proposed Solution
- The Sentiment Analysis team (@sadia-kd  and @SimonYYL ) will implement the final models in sentiment.py, ensuring they work together and adhere to consistent output variables.
- Each model's results should be added to the original json format data.
- Testing will confirm accurate and consistent results.

### Prerequisites
- [x] Finalize the list of models with team members
- [x] Confirm the data format for output

### Steps to Complete
- [x] Update python script with the following models: Textblob, GoEmotion, Comprehend, Python Language Tool
- [x] Use consistent variables names: vcmp_polarity, vcmp_subjectivity, vcmp_emotion, vcmp_sentiment, vcmp_spellingerrors, vcmp_spellingquality
- [x] Update requirements.txt file 
- [x] Write test cases based on sample data to verify output
